# Generated by Django 4.2.2 on 2023-07-06 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('development', 'Permiso como Desarrollador'), ('scrum_master', 'Permiso como scrum_master'), ('product_owner', 'Permiso como Product_Owner')]},
        ),
    ]
