# Generated by Django 4.2.2 on 2023-07-07 00:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='fecha_creacion',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='book',
            name='fecha_modificacion',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
