# Generated by Django 4.2.2 on 2023-07-06 20:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book_fecha_creacion_book_fecha_modificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='book',
            name='fecha_modificacion',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
